spring:
    application:
        name: account-service

    profiles:
        active: ${SPRING_PROFILE:dev}

    datasource:
        url: ${DB_URL:jdbc:postgresql://account-postgres:5432/accountdb}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres123}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true
                "[use_sql_comments]": true
                "[jdbc]":
                    "[batch_size]": 20
                "[order_inserts]": true
                "[order_updates]": true

    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration

    cache:
        type: caffeine
        cache-names: accounts
        caffeine:
            spec: maximumSize=1000,expireAfterWrite=10m

server:
    port: ${SERVER_PORT:8080}
    servlet:
        context-path: /
    compression:
        enabled: true
    http2:
        enabled: true

# Client Service Configuration
services:
    client:
        url: http://client-service:8080

# Resilience4j Configuration
resilience4j:
    circuitbreaker:
        instances:
            clientService:
                register-health-indicator: true
                sliding-window-size: 10
                sliding-window-type: COUNT_BASED
                minimum-number-of-calls: 5
                permitted-number-of-calls-in-half-open-state: 3
                automatic-transition-from-open-to-half-open-enabled: true
                wait-duration-in-open-state: 30s
                failure-rate-threshold: 50
                slow-call-rate-threshold: 100
                slow-call-duration-threshold: 5s
                record-exceptions:
                    - org.springframework.web.client.HttpServerErrorException
                    - org.springframework.web.client.ResourceAccessException
                    - java.net.ConnectException
                    - java.net.SocketTimeoutException
                ignore-exceptions:
                    - org.springframework.web.client.HttpClientErrorException.NotFound

    retry:
        instances:
            clientService:
                max-attempts: 3
                wait-duration: 500ms
                enable-exponential-backoff: true
                exponential-backoff-multiplier: 2
                retry-exceptions:
                    - org.springframework.web.client.ResourceAccessException
                    - java.net.ConnectException
                    - java.net.SocketTimeoutException
                ignore-exceptions:
                    - org.springframework.web.client.HttpClientErrorException

    timelimiter:
        instances:
            clientService:
                timeout-duration: 10s
                cancel-running-future: true

# Actuator Configuration
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus,circuitbreakers,retries
    endpoint:
        health:
            show-details: always
            show-components: always
    health:
        circuitbreakers:
            enabled: true
    prometheus:
        metrics:
            export:
                enabled: true

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        operations-sorter: method
        tags-sorter: alpha

logging:
    level:
        "[org.flywaydb]": DEBUG
        root: INFO
        "[com.scapuz.msa_clients]": DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
