spring:
    docker:
        compose:
            enabled: false
    application:
        name: client-service

    profiles:
        active: ${SPRING_PROFILE:dev}

    datasource:
        url: ${DB_URL:jdbc:postgresql://postgres:5432/clientdb}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres123}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true
                "[use_sql_comments]": true
                "[jdbc]":
                    "[batch_size]": 20
                "[order_inserts]": true
                "[order_updates]": true

    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration

    cache:
        type: caffeine
        cache-names: clients
        caffeine:
            spec: maximumSize=1000,expireAfterWrite=10m

server:
    port: ${SERVER_PORT:8080}
    servlet:
        context-path: /
    compression:
        enabled: true
    http2:
        enabled: true

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
    endpoint:
        health:
            show-details: always
    prometheus:
        metrics:
            export:
                enabled: true

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        operations-sorter: method
        tags-sorter: alpha

logging:
    level:
        org.flywaydb: DEBUG
        root: INFO
        "[com.scapuz.msa_clients]": DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
